apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-naitve-go
  labels:
    app: cloud-naitve-go
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app:  cloud-naitve-go
        tier: service
    spec:
      containers:
      - name: my-go-container
        image: gomicro:2.0.0
        ports:
          -  containerPort: 8080
        env:
        - name: PORT
          value:  '8080'
        resources:
          requests:
            memory: "64Mi"
            cpu:  "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"  
        readinessProbe:
          httpGet: 
            path: /
            port: 8080
          initialDelaySeconds:  5
          timeoutSeconds: 5
        livenessProbe:
          httpGet: 
            path: /
            port: 8080
          initialDelaySeconds:  5
          timeoutSeconds: 5
      

